apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-clima-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-clima
  template:
    metadata:
      labels:
        app: php-clima
    spec:
      containers:
        - name: php-clima-container
          image: php-clima-api:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-clima-service
spec:
  type: NodePort
  selector:
    app: php-clima
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
